baseURL = "https://dbg-lab.github.io/"

# This is a "one page"-website, so we do not need these kinds of pages...
disableKinds = ["section", "taxonomy", "term", "RSS", "robotsTXT"]

# The name of this wonderful theme ;-).
theme = "hugo-scroll"

# The browser tab name
title = "The Goodman Lab"

# In order to add version information in the page's footer set to true.
# enableGitInfo = true

# enable emoji processing in Markdown (valid only for pure markdown content)
enableEmoji = true

# Theme-specific variables `.Site.Params.myParamName`
[params]

    # The path to your "favicon". This should be a square (at least 32px x 32px) png-file.
    favicon = "images/favicon.png"

    # These "images" are used for the structured data templates. This will show up, when
    # services like Twitter or Slack want to generate a preview of a link to your site.
    # See https://gohugo.io/templates/internal#twitter-cards and https://gohugo.io/templates/internal#open-graph.
    # NOT the actual header background image, go to _index.md instead
    images = ["images/cover-image.png"]

    # When set true, it creates a visual guard (partially transparent rounded box), preventing non-ideal background images from interfering with title/description headings
    # Ideal images are homogenous around the centre and contrasting to the text.
    # see CSS classes: .title-and-description-guard, .blog-title, .blog-description
    # see _index.md header_headline and header_subheadline
    title_guard = false

    # Another "title" :-). This one is used as the site_name on the Hugo's internal
    # opengraph structured data template.
    # See https://ogp.me/ and https://gohugo.io/templates/internal#open-graph.
    title = "The Goodman Lab for Synthetic Immunology"

    # The "description" of your website. This is used in the meta data of your generated html.
    description = "Website for the Goodman Lab for Synthetic Immunology at the University of Pennsylvania"

    # Show a menu of languages available
    language_menu = false

    # Show also a language menu item for the current language, if false only
    # show the remaining languages
    show_current_lang = false

    # A "copyright"-line to be added at the bottom of the page.
    # Hint: Plain HTML is supported in here as well. So you may e.g. add a link to your legal imprint-page.
    copyright = "© Daniel Goodman"

    # This theme will, by default, inject a design-by-line at the bottom of the page.
    # You can turn it off, but we would really appreciate if you don't :-)
    hidedesignbyline = false

    # The sections of the home page alternate styling. Mark invert as true to swap the styling of the sections
    invertSectionColors = false

    # Options used for automatic image generation. see: https://gohugo.io/content-management/image-processing/
    image_options = "webp q90 lanczos photo"

    # Use "page_title | site_title" for <title> tags
    # e.g. <title>Legal | Jane Doe - Nutrition Coach & Chef Consultant</title>
    combine_page_and_site_title = false

    [params.footer]
    # Show contact icons for email/phone (if specified) in the footer of the page
    showContactIcons = false

    # Show links indicated with footer_menu and footer_menu_title in the footer of the page
    showFooterLinks = false

    [params.meta]
        keywords = "synthetic immunology, T cells, CAR-T therapy, cancer immunotherapy, synthetic biology, genome engineering, CRISPR, AAV gene delivery, University of Pennsylvania, Penn Medicine, cancer biology, cell therapy, immunotherapy, gene therapy, cellular engineering, cancer research, immune system engineering, adoptive cell therapy, therapeutic T cells, precision medicine"

    [[params.contacts]]
        label = "email"
        value = "goodmand@pennmedicine.upenn.edu"
        url = "mailto:goodmand@pennmedicine.upenn.edu"
        icon = "fa fa-envelope"

    [[params.contacts]]
        label = "address"
        value = "Smilow Center for Translational Research<br>3400 Civic Center Boulevard<br>Philadelphia, PA 19104"
        url = ""
        icon = "fa fa-map-marker"

    # Add additional contacts here!
    # [[params.contacts]]
    #     label = ""
    #     value = ""
    #     url = ""
    #     icon = ""

    [[params.social_links]]
        title = "Download my CV"
        url = "/files/dbg_cv.pdf"  # Adjust this path to where you store your CV
        icon = "custom-cv-icon"  # Custom class for styling
        last = true

    [[params.social_links]]
        title = "Personal Website"
        url = "http://dbgoodman.com"
        icon = "fa-solid fa-globe"

    [[params.social_links]]
        title = "Find my work on Google Scholar"
        url = "https://scholar.google.com/citations?user=j_1Z_l4AAAAJ"
        icon = "fa-solid fa-graduation-cap"  # Font Awesome doesn't have Google Scholar
    
    [[params.social_links]]
        title = "Follow me on Twitter"
        url = "https://twitter.com/dbgoodman"
        icon = "fa-brands fa-twitter"
    
    [[params.social_links]]
        title = "Fork me on GitHub"
        url = "https://github.com/dbgoodman"
        icon = "fa-brands fa-github"
    
    [[params.social_links]]
        title = "Find my work on ORCID"
        url = "http://orcid.org/0000-0003-3759-6883"
        icon = "fa-brands fa-orcid"
    
    
    [[params.social_links]]
        title = "Add me on LinkedIn"
        url = "https://www.linkedin.com/in/dbgoodman/"
        icon = "fa-brands fa-linkedin"